In [1]:
import cv2
from keras.applications.vgg16 import preprocess_input
import base64
import random, json
from keras.models import load_model
import numpy as np

Using TensorFlow backend.


In [2]:
model=load_model('facefeatures_new_model.h5')
face_classifier = cv2.CascadeClassifier('C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\cv2\\data\\haarcascade_frontalface_default.xml')

In [3]:
def face_detector(img):
    faces=face_classifier.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cropped_face=img[y:y+h, x:x+w]
    return cropped_face

In [4]:
video=cv2.VideoCapture(0)

In [6]:
from PIL import Image

while(True):
    _, frame=video.read()
    face=face_detector(frame)
    
    if type(face) is  np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
                     
        name="None matching"
        
        if(pred[0][1] > 0.5):
            name='Vivek Ghosh'
        else:
            name='Papa'
            
        print(pred, name)
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video.release()
cv2.destroyAllWindows()

[[4.635519e-16 1.000000e+00]] Vivek Ghosh
[[1.1998681e-10 1.0000000e+00]] Vivek Ghosh
[[1.3562689e-22 1.0000000e+00]] Vivek Ghosh
[[1.20393565e-24 1.00000000e+00]] Vivek Ghosh
[[1.4544673e-11 1.0000000e+00]] Vivek Ghosh
[[2.809902e-23 1.000000e+00]] Vivek Ghosh
[[7.0572472e-09 1.0000000e+00]] Vivek Ghosh
[[1.0997814e-16 1.0000000e+00]] Vivek Ghosh
[[1.2388249e-18 1.0000000e+00]] Vivek Ghosh
[[4.2234656e-20 1.0000000e+00]] Vivek Ghosh
[[2.0250968e-20 1.0000000e+00]] Vivek Ghosh
[[1.7591408e-18 1.0000000e+00]] Vivek Ghosh
[[4.187894e-22 1.000000e+00]] Vivek Ghosh
[[1.1165706e-26 1.0000000e+00]] Vivek Ghosh
[[9.9962044e-01 3.7953595e-04]] Papa
[[9.9999976e-01 2.0113664e-07]] Papa
[[7.968811e-06 9.999920e-01]] Vivek Ghosh
[[5.8142496e-14 1.0000000e+00]] Vivek Ghosh
[[1.9079372e-23 1.0000000e+00]] Vivek Ghosh
[[7.587933e-20 1.000000e+00]] Vivek Ghosh
[[5.4800944e-15 1.0000000e+00]] Vivek Ghosh
[[2.6881713e-15 1.0000000e+00]] Vivek Ghosh
[[2.3505795e-19 1.0000000e+00]] Vivek Ghosh
